create table
  public.global_inventory (
    red_ml integer null default 0,
    gold integer null default 100,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    id integer generated by default as identity,
    dark_ml integer null default 0,
    total_potions integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potions (
    potion_id bigint generated by default as identity,
    inventory integer null default 0,
    type integer[] null default '{0,0,0,0}'::integer[],
    sku text null,
    price integer null,
    name text null,
    constraint potions_pkey primary key (potion_id)
  ) tablespace pg_default;

  create table
  public.carts (
    cart_id bigint generated by default as identity,
    customer text null,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_id bigint not null,
    quantity integer null default 0,
    potion_id bigint not null,
    constraint cart_items_pkey primary key (cart_id, potion_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (potion_id)
  ) tablespace pg_default;

  create table
  public.gold_ledger_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    gold_changed integer null,
    tick_id bigint null,
    constraint gold_ledger_items_pkey primary key (id),
    constraint gold_ledger_items_tick_id_fkey foreign key (tick_id) references ticks (tick_id)
  ) tablespace pg_default;

  create table
  public.potion_ledger_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_changed integer null,
    tick_id bigint null,
    potion_id bigint null,
    constraint potion_ledger_items_pkey primary key (id),
    constraint potion_ledger_items_potion_id_fkey foreign key (potion_id) references potions (potion_id),
    constraint potion_ledger_items_tick_id_fkey foreign key (tick_id) references ticks (tick_id)
  ) tablespace pg_default;

  create table
  public.barrel_ledger_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    tick_id bigint null,
    red_ml_changed integer not null,
    blue_ml_changed integer not null,
    green_ml_changed integer not null,
    dark_ml_changed integer not null,
    constraint barrel_ledger_items_pkey primary key (id),
    constraint barrel_ledger_items_tick_id_fkey foreign key (tick_id) references ticks (tick_id)
  ) tablespace pg_default;

  create table
  public.ticks (
    tick_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint ticks_pkey primary key (tick_id)
  ) tablespace pg_default;